name: "버그 리포트"
description: "오작동, 회귀, 문서와 다른 동작을 제보합니다."
title: "[Bug] "
labels:
  - bug
  - needs-triage
body:
  - type: input
    id: package-version
    attributes:
      label: 패키지 버전
      placeholder: "예) 1.3.1"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 재현 절차
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected-actual
    attributes:
      label: 기대 동작 / 실제 동작
      placeholder: |
        기대: ...
        실제: ...
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: 참고 자료(선택)
      description: 에러 로그, 스크린샷, 영상 링크 등
  - type: checkboxes
    id: checklist
    attributes:
      label: 확인 사항
      options:
        - label: 중복 이슈를 확인했습니다.
          required: true
