name: "기능 추가 요청"
description: "새 API, 옵션, 개선 아이디어를 제안합니다."
title: "[Feature] "
labels:
  - enhancement
  - needs-triage
body:
  - type: textarea
    id: problem
    attributes:
      label: 해결하고 싶은 문제
      placeholder: "현재 불편한 점을 간단히 적어주세요."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: 제안하는 해결 방식
      placeholder: "원하는 API/동작을 간단히 적어주세요."
    validations:
      required: true
  - type: input
    id: scope
    attributes:
      label: 영향 범위(선택)
      placeholder: "예) InfoWindow, MarkerClusterer"
  - type: textarea
    id: notes
    attributes:
      label: 참고 자료(선택)
      description: 레퍼런스 링크, 스크린샷, 코드 예시 등
  - type: checkboxes
    id: checklist
    attributes:
      label: 확인 사항
      options:
        - label: 기존 이슈/문서를 확인했습니다.
          required: true
